name: AutoMod
version: '${version}'
main: it.unilix.automod.AutoMod
api-version: '1.20'
load: POSTWORLD
softdepend:
  - LiteBans
commands:
  automod:
    description: 'AutoMod command'
    usage: '/automod'
    permission: 'automod.command'
    aliases:
    - am
    - autom