name: AutoMod
version: '${version}'
main: it.unilix.automod.AutoMod
api-version: '1.17'
load: POSTWORLD
libraries:
  - com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.17.1
  - com.fasterxml.jackson.core:jackson-databind:2.16.1
  - io.lettuce:lettuce-core:6.2.5.RELEASE

softdepend:
  - LiteBans
commands:
  automod:
    description: 'AutoMod command'
    usage: '/automod'
    permission: 'automod.command'
    aliases:
    - am
    - autom
  automodmsg:
    description: 'AutoMod message command'
    usage: '/automodmsg <message>'
    permission: 'automod.command'
    aliases:
    - ammsg
    - automsg
    - msg
  automodresponse:
    description: 'AutoMod response command'
    usage: '/automodresponse <response>'
    permission: 'automod.command'
    aliases:
    - amresponse
    - autoresponse
    - response
    - r


permissions:
  automod.command:
      description: 'AutoMod command'
      default: op
  automod.bypass:
    description: 'Bypass AutoMod'
    default: op
  automod.staff:
    description: 'Staff AutoMod'
    default: op
