name: AutoMod
version: '${version}'
main: it.unilix.automod.AutoMod
api-version: '1.20'
load: POSTWORLD
libraries:
  - com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.17.1
  - com.fasterxml.jackson.core:jackson-databind:2.16.1

softdepend:
  - LiteBans
commands:
  automod:
    description: 'AutoMod command'
    usage: '/automod'
    permission: 'automod.command'
    aliases:
    - am
    - autom

permissions:
  automod.command:
      description: 'AutoMod command'
      default: op
  automod.bypass:
    description: 'Bypass AutoMod'
    default: op
  automod.staff:
    description: 'Staff AutoMod'
    default: op