name: AutoMod
version: '${version}'
main: com.nextdevv.automod.AutoMod
api-version: '1.17'
load: POSTWORLD
libraries:
  - com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.17.1
  - com.fasterxml.jackson.core:jackson-databind:2.16.1
  - io.lettuce:lettuce-core:6.2.5.RELEASE
  - org.jooq:joor:0.9.15
  - com.fasterxml.jackson.core:jackson-annotations:2.18.0

softdepend:
  - LiteBans

commands:
  automod:
    description: 'AutoMod command'
    usage: '/automod'
    permission: 'automod.command'
    aliases:
    - am
    - autom
  message:
    description: 'Message a player'
    usage: '/message <player> <message>'
    aliases:
      - msg
      - m
  reply:
    description: 'Reply to a player'
    usage: '/reply <message>'
    aliases:
      - r
  ignore:
    description: 'Ignore a player'
    usage: '/ignore <player>'
    aliases:
      - ig
  report:
    description: 'Report a player'
    usage: '/report <player> <reason>'
    aliases:
      - rep

permissions:
  automod.command:
      description: 'AutoMod command'
      default: op
  automod.bypass:
    description: 'Bypass AutoMod'
    default: op
  automod.staff:
    description: 'Staff AutoMod'
    default: op
  automod.reports:
    description: 'View reports'
    default: op
  automod.spy-dms:
    description: 'Spy on dms'
    default: op
