package com.nextdevv.automod.enums;

public enum Attribute {
    TOXICITY,
    SEVERE_TOXICITY,
    IDENTITY_ATTACK,
    INSULT,
    PROFANITY,
    THREAT,
    TOXICITY_EXPERIMENTAL,
    SEVERE_TOXICITY_EXPERIMENTAL,
    IDENTITY_ATTACK_EXPERIMENTAL,
    INSULT_EXPERIMENTAL,
    PROFANITY_EXPERIMENTAL,
    THREAT_EXPERIMENTAL,
    SEXUALLY_EXPLICIT,
    FLIRTATION
}
